### ISSUE TITLE
Horizontal scrolling with middle-click

### ISSUE THREAD

**Issue by jdepypere** [winhowes/parallax-container#5] opened 2016-01-09 10:59 UTC
[As someone mentioned on SO](http://stackoverflow.com/questions/34670714/how-to-achieve-this-in-polymer) it appears to be possible to, by doing a 'middle click' (eg clicking the mouse wheel), to scroll horizontally, even though there are no horizontal scroll bars. I haven't looked into it too much, but on desktop it does seem to be a rather big issue worth fixing.

Looking into this a bit further there seem to be many issues due to this behaviour and probably has to do with `overflow-x: hidden;`.

**Comment by winhowes** [comment] 2016-01-18 08:46
This seems to be a duplicate of #4 which is an issue with webkit unfortunately :/. Are you able to generate this issue in Firefox or another non-webkit based browser? I believe there is a bug filed with webkit over this very issue. The only work around I know of would require a fairly big rewrite with some potentially intrusiveJS

**Closed** 2016-01-18 09:23 UTC

**Comment by winhowes** [comment] 2016-01-18 09:31
I wrote a temporary js fix - which shouldn't be too intrusive

**Comment by jdepypere** [comment] 2016-01-18 21:12
Neat and clean fix - sorry I didn't check the closed issues for any previous issues regarding this issue. I tried a tad myself to fix it, but couldn't get it working.
